# Welcome to Jekyll!
#

# Site settings
title: POI'S BLOG
description: |
  Weclome to my place!  
  I will write some random stuff  
  of my life here. Just for fun!
owner: POI WANG # Your Name or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: b07302230@ntu.edu.tw # your-email@domain.com
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://poi0905.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
